appConfig:
  theme: nord-frost
  layout: auto
  iconSize: large
  language: en
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: false
  statusCheckInterval: 0
  backgroundImg: >-
    https://wallpapers.com/images/hd/dark-laptop-galaxy-and-space-m8yf12xuodz5871c.jpg
  faviconApi: allesedv
  routingMode: history
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: true
    hideNav: true
    hideSearch: true
    hideSettings: true
    hideFooter: true
  auth:
    enableGuestAccess: true
    users:
      - user: nica
        hash: 66a5b86b0e8bf6efff749031f95a3a0f2f6d966896506707413ff9abb53e11a8
        type: admin
    enableKeycloak: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  disableConfigurationForNonAdmin: true
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
pageInfo:
  title: Dashy
  description: Hi üëã
  navLinks:
    - title: ‚òÄÔ∏è
      path: https://sun.org/
      target: newtab
  footerText: ''
sections:
  - name: Home
    icon: üè†
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: true
    items:
      - &ref_0
        title: Pihole
        icon: >-
          https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/cropped-Vortex-R-32x32.png
        url: http://pihole.10.0.0.37.sslip.io/admin/login.php
        id: 0_393_pihole
      - &ref_1
        title: Router
        icon: far fa-download
        url: http://router.home/
        id: 1_393_router
      - &ref_2
        title: Deco
        icon: far fa-rss
        url: http://tplink-deco.home/webpages/index.html
        id: 2_393_deco
      - &ref_3
        title: Traefik
        icon: https://traefik.io/favicon.svg
        url: http://homelab5g.home:8080/dashboard
        id: 3_393_traefik
    filteredItems:
      - *ref_0
      - *ref_1
      - *ref_2
      - *ref_3
  - name: Tools
    icon: üîß
    displayData:
      sortBy: random
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: true
    items:
      - &ref_4
        title: Discord Embed Builder
        icon: >-
          https://dpo5b3b56op9b.cloudfront.net/content/autocode/release/static/branding/favicon-01-1f86a9d1.webp
        url: https://autocode.com/tools/discord/embed-builder/
        id: 0_529_discordembedbuilder
    filteredItems:
      - *ref_4
  - name: Public
    icon: üñ•Ô∏è
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: true
    items:
      - &ref_5
        title: Coolify
        icon: https://coolify.io/coolify-transparent.png
        url: https://nikasol.xyz/
        id: 0_607_coolify
      - &ref_6
        title: UpSnap
        icon: https://upsnap.nikasol.xyz/gopher.svg
        url: https://upsnap.nikasol.xyz/login/
        id: 1_607_upsnap
      - &ref_7
        title: Moonlight Streaming
        icon: https://moonlight-stream.org/images/manifest/icons-96.png
        url: https://moonlight.nikasol.xyz/
        id: 2_607_moonlightstreaming
    filteredItems:
      - *ref_5
      - *ref_6
      - *ref_7
  - name: Apps
    icon: üé™
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - &ref_8
        title: Pokemon GYM Tracker
        icon: https://pokemon-gym-tracker.nikasol.xyz/masterball.svg
        url: https://pokemon-gym-tracker.nikasol.xyz/
        id: 0_404_pokemongymtracker
    filteredItems:
      - *ref_8
  - name: Media
    icon: üì∫
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: true
    items:
      - &ref_9
        title: Plex
        icon: https://plex.nikasol.xyz/web/favicon.ico
        url: https://plex.nikasol.xyz/web/index.html#!/
        id: 0_480_plex
      - &ref_10
        title: Jellyfin
        icon: https://jellyfin.nikasol.xyz/web/bc8d51405ec040305a87.ico
        url: https://jellyfin.nikasol.xyz/web/index.html#!/home.html
        id: 1_480_jellyfin
    filteredItems:
      - *ref_9
      - *ref_10

